### ISSUE TITLE
Add `named-grid-areas-alignment` rule

### ISSUE THREAD

**Issue by MorevM** [stylelint-stylistic/stylelint-stylistic#15]
### What is the problem you're trying to solve?

Hello, first of all thank you for your work :)

I've been thinking for quite some time about a rule that would format the `grid-template-areas` value into a table, illustrated:

### Input:
```scss
.block {
  grid-template-areas:
    'column another another . a d'
    'column foo foo . e .'
    'longest-one foo foo . bar bar';
}
```

### Output:
```scss
.block {
  grid-template-areas:
    'column       another  another  .  a    d'
    'column       foo      foo      .  e    .'
    'longest-one  foo      foo      .  bar  bar';
}
```

From experience, this can dramatically improve readability.

### What solution would you like to see?

I could implement this rule in the scope of this package, if you're interested. 
In that case, we can discuss options and edge cases here.

If you want to keep the package only for rules that were originally in Stylelint - no problem, I'll make a separate plugin for that :)
By the way, ESLint Stylistic already [introduced few new rules](https://eslint.style/packages/plus) in addition to ESLint's original stylistic rules.

What are your thoughts on this?

**Comment by firefoxic** [comment]
@MorevM Thanks for the proposal. 

> If you want to keep the package only for rules that were originally in Stylelint

No, the plugin should not be a frozen form of the rules removed from Stylelint. Additions and enhancements are welcome!
Perhaps we should be more explicit about this, not just with [this short sentence](https://github.com/stylelint-stylistic/stylelint-stylistic/tree/main#:~:text=new%20rules%20may%20be%20added).

> I could implement this rule in the scope of this package, if you're interested.

Thank you!!! That would be great!

I've labeled the issue as ready to implement. Please check out [CONTRIBUTING.md](https://github.com/stylelint-stylistic/stylelint-stylistic/blob/main/CONTRIBUTING.md).
There are [steps on how to add a new rule](https://github.com/stylelint-stylistic/stylelint-stylistic/blob/main/docs/developer-guide/rules.md#add-a-rule) in the Developer guide.

**Comment by firefoxic** [comment]
It seems that the name of the new rule should start with `named-grid-areas-` for consistency with the upstream rule [named-grid-areas-no-invalid](https://stylelint.io/user-guide/rules/named-grid-areas-no-invalid). But the ending needs some thought 🤔

**Comment by firefoxic** [comment]
In this example, the column gap is 2 spaces:
```css
.block {
  grid-template-areas:
    'column       another  another  .  a    d'
    'column       foo      foo      .  e    .'
    'longest-one  foo      foo      .  bar  bar';
}
```
Perhaps we need an option to control the size of this gap.

And about closing quotes — should they be aligned in a column? E.g. like this:
```css
.block {
  grid-template-areas:
    'column       another  another  .  a    d  '
    'column       foo      foo      .  e    .  '
    'longest-one  foo      foo      .  bar  bar';
}
```

**Comment by MorevM** [comment]
I would like to see this named `named-grid-areas-table-alignment` name with `true` as a primary option, and an object of form `{ spacesBetween: number; trailingSpaces: boolean; quotes: 'single' | 'double'; newLine: 'never' | 'always' | 'always-multiline' }` as a secondary option. What do you think?

Also, we need to decide what to do with invalid values, example:
```scss
.block {
  grid-template-areas:
    'foo  bar'
    'bar  foo';
}
```

Technically, this is invalid property syntax, but that doesn't prevent from formatting the rows as a table.

I would make the rule format the value regardless of its validity - after all, there is a `named-grid-areas-no-invalid` rule for that.
If I implement the validation inside a new rule, the old one will be completely absorbed and become useless, and the code of this rule will become much more complicated (which I would like to avoid). But willing to hear an alternative opinion :)
