### ISSUE TITLE
Add the `grid-flexible-track-no-content-minimum` rule

### ISSUE THREAD

**Issue by MorevM** [stylelint-stylistic/stylelint-stylistic#28]
### What is the problem you're trying to solve?

Hello,
I have an idea for a rule to keep the user safe from "grid blowout" problem.

**Context:**
https://css-tricks.com/preventing-a-grid-blowout/

**Another good article with examples of the problem:**
https://defensivecss.dev/tip/grid-min-content-size/

**Illustrative pen with the problem:**
https://codepen.io/joakimc/pen/ZEbgVLZ

**And, finally, my pen illustrating the problem and its possible solutions**
*Solutions are commented, uncomment each to see how it solves the problem:*
https://codepen.io/morevm/pen/JjqyWRe

### What solution would you like to see?

Let's imagine we have a rule such as `grid-fr-safe` (discussable), that will recommend replacing `Xfr` with `minmax(0, Xfr)` (with possible autofix):
```scss
// Before
.grid {
  grid-template-columns: repeat(12, 1fr);
}

// After
.grid {
  grid-template-columns: repeat(12, minmax(0, 1fr));
}
```

This is ultimative solution to prevent the problem, but there are some but there are a few controversial points:

- **It might be too verbose in a compex layout, so less readable**

  ```scss
  .grid {
    grid-template-columns: 300px 1fr 2fr 400px;
  }

  .grid {
    grid-template-columns: 300px minmax(0, 1fr) minmax(0, 2fr) 400px;
  }
  ```

- **The problem may already be solved in another way**
  And we're pretty limited in taking that into account.
  
  Let's say we have a markup and its styles to analyze (the note Stylelint doesn't know anything about markup):
  ```html
  <div class="grid grid-context">
    <div class="grid__item"><!-- --></div>
    <div class="grid__item"><!-- --></div>
  </div>
  ```

  ```scss
  .grid {
    grid-template-columns: 1fr 300px;
  }
  ```

  The user may have one of following: 
  ```scss
  // We can't be sure it applies to the proper context (and only to)
  .grid__item { min-width: 0; }
  .grid-context > * { overflow: hidden; }
  .grid > * { min-width: 0; }
  ```

  So, if the user already have a solution, the rule will solve a problem that doesn't exist.
  Feels more reliable, but verbose, again..
  Although many (myself included) think it's more robust to declare this in the grid selector rather than in their elements (something like [margin-trim](https://developer.mozilla.org/en-US/docs/Web/CSS/margin-trim) instead of resetting the margin of the last element)

- **Should this apply to `grid-template-rows` as well?**
  I've never had a problem with it, but technically, you could come up with a scenario where it would be needed.

I would be happy to provide a solution that would apply exclusively if no other solution is already exists, but actually the only thing we can check is the selector `{grid-template-columns-rule-selector} > *`.

I'd love to hear any opinions for or against.
At the moment I think that the `grid-fr-safe` rule with the `{ autofix: boolean }` option might make sense.
