### ISSUE TITLE
Is there any rules about moving the declaration above the nested rule ?

### ISSUE THREAD

**Issue by l-outsider** [stylelint-stylistic/stylelint-stylistic#34]
### Describe the documentation issue

sass in my project report some warning

> Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`.

because the following structure:

```scss
.parent {
    .child {
        // some property
    }

    width: 100px;
}
```

it means i must move css declarations of parent above nested scss, like this:

```scss
.parent {
    width: 100px;

    .child {
        // some property
    }
}
```

so, I try to find some rules to achieve this structure. thanks.

### What solution would you like to see?

Are there any existing rules that can achieve this restriction? If not, can it be supported?
