### ISSUE TITLE
Add new line before @include 

### ISSUE THREAD

**Issue by TheElegantCoding** [stylelint-stylistic/stylelint-stylistic#46]
### What is the problem you're trying to solve?

This is considered a problem

```scss
.section-hero
{
  padding-bottom: $spacing_64;
  @include responsive(small_desktop)
  {
    flex-direction: row;
    padding-top: $spacing_160;
  }
}
```

### What solution would you like to see?

This is the correct way

```scss
.section-hero
{
  padding-bottom: $spacing_64;

  @include responsive(small_desktop)
  {
    flex-direction: row;
    padding-top: $spacing_160;
  }
}
```
