### ISSUE TITLE
Support null value (space char) for css properties in @stylistic/declaration-block-semicolon-space-before

### ISSUE THREAD

**Issue by kerryj89** [stylelint-stylistic/stylelint-stylistic#50]
### What minimal example or steps are needed to reproduce the bug?

```css
.block{
  --turn-amount: rotate(45deg) rotate(13deg);
  --scale-amount: 3;
  aspect-ratio: 1/1;
  width: 100px;
  background: blue;
  transform: var(--turn-amount) scale(var(--scale-amount));
}
.block-1{
  --turn-amount: ; // Unexpected whitespace before ";" (@stylistic/declaration-block-semicolon-space-before)Stylelint[@stylistic/declaration-block-semicolon-space-before](https://github.com/stylelint-stylistic/stylelint-stylistic/blob/main/lib/rules/declaration-block-semicolon-space-before/README.md)
}
```

### What minimal configuration is needed to reproduce the bug?

```json
{
  "extends": [
    "stylelint-config-standard"
  ],
  "rules": {
    "@stylistic/declaration-block-semicolon-space-before": "never"
  }
}
```

### How did you run Stylelint?

[Demo](https://stylelint.io/demo/#N4Igxg9gJgpiBcICGACYAdAdugLgWjxxgGcd4UBuLAXxABoQAzASwBsYA5JAWzkRgAePAA7sAdGGLF64CJhYBzBCAyYUKdCFEBXBc0zFN5ANpZc5kAAFSAT1bNSzMAHpb7e5nw692EGZwAunRY6pqCRJhQhggopmrqGiBuMB74kPLMCnikSJFIAE5QmiEoQSWa+drs0eSqCYnWOHYOOE7OsGCsBUitcngARqwQYADW2TDcThBDmNnCSGAwAzCMEPkwRomYMABuMPnF8dQ0MumKAGJr3D3KAFbEcjKwwtKIdYnJqZuaXUSkmsF4ppPvo0nJFNkcLkoAUijEfj0SDgAeUrG4Wm0QZ48N59N8QL8kYdaNQgA)

### Which Stylelint-related dependencies are you using?

Latest in demo

### What did you expect to happen?

Ignore for css property in this situation because `--variable: ;` is a valid null representation.

### What actually happened?

// Unexpected whitespace before ";" (@stylistic/declaration-block-semicolon-space-before)Stylelint[@stylistic/declaration-block-semicolon-space-before](https://github.com/stylelint-stylistic/stylelint-stylistic/blob/main/lib/rules/declaration-block-semicolon-space-before/README.md)

### Do you have a proposal to fix the bug?

Add a check to see if it's the property is a css variable, in that case don't apply the rule if only a space character exists.

Thanks for maintaining this!
